# Generated by Django 3.0.5 on 2020-04-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='owner_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
