# Generated by Django 3.0.5 on 2020-04-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20200408_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
