# Generated by Django 3.1.7 on 2021-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210522_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Jobs', 'Jobs'), ('Property', 'Property'), ('Electronics', 'Electronics'), ('Cars', 'Cars'), ('Books&Sports', 'Books&Sports'), ('Mobiles', 'Mobiles'), ('Bikes', 'Bikes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('OD', 'Odisha'), ('MP', 'Madhya Pradesh'), ('BR', 'Bihar'), ('MN', 'Manipur'), ('KA', 'Karnataka'), ('AS', 'Assam'), ('WB', 'West Bengal'), ('PB', 'Punjab'), ('UP', 'Uttar Pradesh'), ('TN', 'Tamil Nadu'), ('KL', 'Kerala'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('RJ', 'Rajasthan'), ('NL', 'Nagaland'), ('CG', 'Chhattisgarh'), ('TS', 'Telegana'), ('ML', 'Meghalaya'), ('UK', 'Uttarakhand'), ('HP', 'Haryana'), ('MH', 'Maharashtra'), ('JH', 'Jharkhand'), ('AR', 'Arunachal Pradesh'), ('MZ', 'Mizoram'), ('TR', 'Tripura'), ('MI', 'Sikkim')], max_length=100),
        ),
    ]
