# Generated by Django 3.1.7 on 2021-05-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20210522_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='no_of_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Bikes', 'Bikes'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs'), ('Cars', 'Cars'), ('Property', 'Property'), ('Books&Sports', 'Books&Sports'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('ML', 'Meghalaya'), ('NL', 'Nagaland'), ('AR', 'Arunachal Pradesh'), ('OD', 'Odisha'), ('CG', 'Chhattisgarh'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('BR', 'Bihar'), ('TS', 'Telegana'), ('TN', 'Tamil Nadu'), ('JH', 'Jharkhand'), ('HP', 'Haryana'), ('AS', 'Assam'), ('TR', 'Tripura'), ('UK', 'Uttarakhand'), ('PB', 'Punjab'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('KL', 'Kerala'), ('MN', 'Manipur'), ('AP', 'Andhra Pradesh'), ('MH', 'Maharashtra'), ('MZ', 'Mizoram'), ('MP', 'Madhya Pradesh'), ('KA', 'Karnataka'), ('MI', 'Sikkim'), ('RJ', 'Rajasthan')], max_length=100),
        ),
    ]
