category_choices = {
  'Electronics': 'Electronics',
  'Property': 'Property',
  'Cars': 'Cars',
  'Furniture': 'Furniture',
  'Jobs': 'Jobs',
  'Mobiles': 'Mobiles',
  'Bikes': 'Bikes',
  'Books&Sports': 'Books&Sports',
  'Fashion': 'Fashion'
  }

price_choices = {
  '1000':'₹1,000',
  '2000':'₹2,000',
  '5000':'₹5,000',
  '10000':'₹10,000',
  '20000':'₹20,000',
  '50000':'₹50,000',
  '100000':'₹100,000',
  '200000':'₹200,000',
  '500000':'₹500,000',
  '1000000':'₹1M+',
  
}

state_choices = {
  'AP': 'Andhra Pradesh',
  'AR': 'Arunachal Pradesh',
  'AS': 'Assam',
  'BR': 'Bihar',
  'CG': 'Chhattisgarh',
  'GA': 'Goa',
  'GJ': 'Gujarat',
  'HP': 'Haryana',
  'JH': 'Jharkhand',
  'KA': 'Karnataka',
  'KL': 'Kerala',
  'MP': 'Madhya Pradesh',
  'MH': 'Maharashtra',
  'MN': 'Manipur',
  'ML': 'Meghalaya',
  'MZ': 'Mizoram',
  'NL': 'Nagaland',
  'OD': 'Odisha',
  'PB': 'Punjab',
  'RJ': 'Rajasthan',
  'MI': 'Sikkim',
  'TN': 'Tamil Nadu',
  'TS': 'Telegana',
  'TR': 'Tripura',
  'UP': 'Uttar Pradesh',
  'UK': 'Uttarakhand',
  'WB': 'West Bengal',
}